package com.atmecs.dataprovider;

// Generated by Selenium IDE
import java.util.HashMap;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class HomePageTesting {
	FindLocaters locaters = new FindLocaters();

	public static void main(String[] args) {
		setUp();
	}

	private static WebDriver driver;

	@Before
	public static void setUp() {
		driver = new ChromeDriver();
		new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void tESTHOME() {
		driver.get("https://www.orangehrm.com/");
		driver.manage().window().maximize();
		driver.findElement(By.id("cta_button_3749854_7956a89e-6f16-4650-8d49-9f825d5cc7d6")).click();
		driver.findElement(By.id(FindLocaters.getLocater("firstname"))).click();
		driver.findElement(By.id(FindLocaters.getLocater("firstname"))).sendKeys("saurabh");
		driver.findElement(By.id(FindLocaters.getLocater("last name"))).sendKeys("chauhan");
		driver.findElement(By.id(FindLocaters.getLocater("url_here"))).click();
		driver.findElement(By.id(FindLocaters.getLocater("Bussiness email"))).sendKeys("chauhaninfj@gmail.com");
		driver.findElement(By.id(FindLocaters.getLocater("job title"))).sendKeys("engineer");
		driver.findElement(By.id(FindLocaters.getLocater("no of employees"))).click();
		{
			WebElement dropdown = driver.findElement(By.id(FindLocaters.getLocater("no of employees")));
			dropdown.findElement(By.xpath("//option[. = '401 - 450']")).click();
		}
		driver.findElement(By.id(FindLocaters.getLocater("no of employees"))).click();
		driver.findElement(By.id(FindLocaters.getLocater("company name"))).click();
		driver.findElement(By.id(FindLocaters.getLocater("company name"))).sendKeys("Atmecs");
		driver.findElement(By.id(FindLocaters.getLocater("industry"))).click();
		{
			WebElement dropdown = driver.findElement(By.id(FindLocaters.getLocater("industry")));
			dropdown.findElement(By.xpath("//option[. = 'Computer / Technology - Services / Consultancy']")).click();
		}
		driver.findElement(By.id(FindLocaters.getLocater("industry"))).click();
		driver.findElement(By.id(FindLocaters.getLocater("phone no"))).click();
		driver.findElement(By.id(FindLocaters.getLocater("phone no"))).sendKeys("9179424242");
		driver.findElement(By.id(FindLocaters.getLocater("country"))).click();
		{
			WebElement dropdown = driver.findElement(By.id(FindLocaters.getLocater("country")));
			dropdown.findElement(By.xpath("//option[. = 'India']")).click();
		}
		driver.findElement(By.id(FindLocaters.getLocater("submit"))).click();
	}
}
